[build]
builder = "NIXPACKS"
buildCommand = "bun install"

[build.nixpacksPlan.phases.setup]
nixPkgs = ["bun"]

[deploy]
startCommand = "bun run src/index.ts"
restartPolicyType = "ON_FAILURE"
numReplicas = 1
